[package]
name = "nerd2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.10.3"
poise = "0.5.5"
tokio = { version = "1.28.2", features = ["full"] }
